name: Sync to Org Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (RiseUp)
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "nahom-bot"
          git config --global user.email "nahom@users.noreply.github.com"

      - name: Clone the Org Repo (Qmem-Tech/Qmem-Website)
        run: |
          git clone https://x-access-token:${{ secrets.ORG_PUSH_TOKEN }}@github.com/Qmem-Tech/Qmem-Website.git
          cd Qmem-Website

      - name: Copy files from RiseUp to Qmem-Website
        run: |
          # Remove all files in Qmem-Website except .git to preserve its Git history
          cd Qmem-Website
          find . -maxdepth 1 -not -path './.git' -not -path . -exec rm -rf {} +
          # Copy all files from RiseUp (parent directory) except .git
          cp -r ../* .
          # Remove the .git from RiseUp to avoid copying it
          rm -rf .git

      - name: Commit & Push to Org Repo
        run: |
          cd Qmem-Website
          git add .
          git commit -m "🔄 Auto-sync from RiseUp on $(date)" || echo "No changes to commit"
          git push origin main
