name: Sync to Org Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "nahom-bot"
          git config --global user.email "nahom@users.noreply.github.com"

      - name: Clone the org repo
        run: |
          git clone https://x-access-token:${{ secrets.ORG_PUSH_TOKEN }}@github.com/Qmem-Tech/Qmem-Website.git org-repo
          rsync -av --delete --exclude='.git' ./ ./org-repo/

      - name: Commit & Push
        run: |
          cd org-repo
          git add .
          git commit -m "🔄 Auto-sync from RiseUp on $(date)" || echo "No changes to commit"
          git push origin main
