name: Sync to Org Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo (RiseUp)
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.name "nahom-bot"
          git config --global user.email "nahom@users.noreply.github.com"

      - name: Set git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Clone Qmem-Website
        run: |
          git clone https://x-access-token:${{ secrets.ORG_PUSH_TOKEN }}@github.com/Nahomtewodros101/RiseUp.git
    

          
      - name: Copy files from RiseUp to Qmem-Website
        run: |
          cd Qmem-Website
          find . -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
          cd ..
          rsync -av --exclude='Qmem-Website' --exclude='.git' ./ Qmem-Website/

      - name: Commit & Push to Org Repo
        run: |
          cd Qmem-Website
          git add .
          git commit -m "🔄 Auto-sync from RiseUp on $(date)" || echo "No changes to commit"
          git push origin main
